name = "serverless-api"
type = "javascript"
zone_id = ""
account_id = "49e76b46858faca307cff13c1d25e3f2"
route = ""
workers_dev = true
compatibility_date = "2021-11-13"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
